/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package login;

/**
 *
 * @author Admin
 */
public class log extends javax.swing.JPanel
{

    /**
     * Creates new form Log
     */
    public log ()
    {
        initComponents ();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings ("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        Usuario = new javax.swing.JLabel();
        T_Usuario = new javax.swing.JTextField();
        Perfil_Usuario = new javax.swing.JLabel();
        Recuerdame = new javax.swing.JCheckBox();
        B_Login = new javax.swing.JButton();
        Contraseña = new javax.swing.JLabel();
        T_Contraseña = new javax.swing.JTextField();
        Welcome = new javax.swing.JLabel();
        P_White = new javax.swing.JLabel();
        Small_Purple = new javax.swing.JLabel();
        Big_Purple = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1000, 520));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(1010, 540));
        jPanel1.setPreferredSize(new java.awt.Dimension(1000, 520));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Usuario.setBackground(new java.awt.Color(73, 80, 87));
        Usuario.setForeground(new java.awt.Color(73, 80, 87));
        Usuario.setText("Usuario");
        jPanel2.add(Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));
        jPanel2.add(T_Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 340, 30));

        Perfil_Usuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Avatar_Container.png"))); // NOI18N
        Perfil_Usuario.setLabelFor(this);
        jPanel2.add(Perfil_Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, -1, -1));

        Recuerdame.setForeground(new java.awt.Color(73, 80, 87));
        Recuerdame.setText("Recuerdame");
        Recuerdame.setBorder(null);
        Recuerdame.setContentAreaFilled(false);
        jPanel2.add(Recuerdame, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, -1));

        B_Login.setBackground(new java.awt.Color(85, 110, 230));
        B_Login.setForeground(new java.awt.Color(255, 255, 255));
        B_Login.setText("Login");
        B_Login.setBorder(null);
        B_Login.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                B_LoginActionPerformed(evt);
            }
        });
        jPanel2.add(B_Login, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 340, 30));

        Contraseña.setBackground(new java.awt.Color(73, 80, 87));
        Contraseña.setForeground(new java.awt.Color(73, 80, 87));
        Contraseña.setText("Contraseña");
        jPanel2.add(Contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));
        jPanel2.add(T_Contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 340, 30));

        Welcome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Card_Header.png"))); // NOI18N
        Welcome.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(Welcome, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, -1));

        P_White.setForeground(new java.awt.Color(0, 0, 0));
        P_White.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Card_Content.png"))); // NOI18N
        P_White.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(P_White, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 420, 300));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 70, 420, 410));

        Small_Purple.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bk2.png"))); // NOI18N
        jPanel1.add(Small_Purple, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 410, -1, -1));

        Big_Purple.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Union.png"))); // NOI18N
        jPanel1.add(Big_Purple, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 540));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1010, 540));
    }// </editor-fold>//GEN-END:initComponents

    private void B_LoginActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_B_LoginActionPerformed
    {//GEN-HEADEREND:event_B_LoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B_LoginActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B_Login;
    private javax.swing.JLabel Big_Purple;
    private javax.swing.JLabel Contraseña;
    private javax.swing.JLabel P_White;
    private javax.swing.JLabel Perfil_Usuario;
    private javax.swing.JCheckBox Recuerdame;
    private javax.swing.JLabel Small_Purple;
    private javax.swing.JTextField T_Contraseña;
    private javax.swing.JTextField T_Usuario;
    private javax.swing.JLabel Usuario;
    private javax.swing.JLabel Welcome;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
