/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package login;

import java.awt.Color;

/**
 *
 * @author Sammy Guergachi <sguergachi at gmail.com>
 */
public class login extends javax.swing.JFrame {

    int xMouse,yMouse;
    public login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel2 = new javax.swing.JPanel();
        Usuario = new javax.swing.JLabel();
        T_Usuario = new javax.swing.JTextField();
        Perfil = new javax.swing.JLabel();
        Recuerdame = new javax.swing.JCheckBox();
        Login = new javax.swing.JButton();
        Contraseña = new javax.swing.JLabel();
        T_Contraseña = new javax.swing.JTextField();
        Welcome = new javax.swing.JLabel();
        Padlocked = new javax.swing.JLabel();
        Forget_Password = new javax.swing.JButton();
        P_White = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        Small_Purple = new javax.swing.JLabel();
        Copyright = new javax.swing.JLabel();
        header = new javax.swing.JPanel();
        exitBtn = new javax.swing.JPanel();
        exitTxt = new javax.swing.JLabel();
        Big_Purple = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Usuario.setForeground(new java.awt.Color(73, 80, 87));
        Usuario.setText("Usuario");
        jPanel2.add(Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        T_Usuario.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mousePressed(java.awt.event.MouseEvent evt)
            {
                T_UsuarioMousePressed(evt);
            }
        });
        T_Usuario.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                T_UsuarioActionPerformed(evt);
            }
        });
        jPanel2.add(T_Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 390, 40));

        Perfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Avatar_Container.png"))); // NOI18N
        jPanel2.add(Perfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, -1, -1));

        Recuerdame.setForeground(new java.awt.Color(73, 80, 87));
        Recuerdame.setText("Recuerdame");
        Recuerdame.setBorder(null);
        Recuerdame.setContentAreaFilled(false);
        Recuerdame.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(Recuerdame, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, -1, -1));

        Login.setBackground(new java.awt.Color(85, 110, 230));
        Login.setForeground(new java.awt.Color(255, 255, 255));
        Login.setText("Login");
        Login.setBorder(null);
        Login.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Login.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mousePressed(java.awt.event.MouseEvent evt)
            {
                LoginMousePressed(evt);
            }
        });
        Login.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                LoginActionPerformed(evt);
            }
        });
        jPanel2.add(Login, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 390, 40));

        Contraseña.setForeground(new java.awt.Color(73, 80, 87));
        Contraseña.setText("Contraseña");
        jPanel2.add(Contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, -1));

        T_Contraseña.setText("********");
        T_Contraseña.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mousePressed(java.awt.event.MouseEvent evt)
            {
                T_ContraseñaMousePressed(evt);
            }
        });
        jPanel2.add(T_Contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 390, 40));

        Welcome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Card_Header.png"))); // NOI18N
        Welcome.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(Welcome, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, -1));

        Padlocked.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Lock.png"))); // NOI18N
        jPanel2.add(Padlocked, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 440, 20, -1));

        Forget_Password.setForeground(new java.awt.Color(116, 120, 141));
        Forget_Password.setText("¿Olvidaste la contraseña?");
        Forget_Password.setBorder(null);
        Forget_Password.setBorderPainted(false);
        Forget_Password.setContentAreaFilled(false);
        Forget_Password.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Forget_Password.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                Forget_PasswordActionPerformed(evt);
            }
        });
        jPanel2.add(Forget_Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 440, 190, 20));

        P_White.setForeground(new java.awt.Color(0, 0, 0));
        P_White.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Card_Content.png"))); // NOI18N
        P_White.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(P_White, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 450, 360));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 6, 450, 470));

        jPanel1.setBackground(new java.awt.Color(244, 243, 243));
        jPanel1.setForeground(new java.awt.Color(60, 63, 65));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Small_Purple.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bk2.png"))); // NOI18N
        jPanel1.add(Small_Purple, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 400, 160, 140));

        Copyright.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Copyright.setForeground(new java.awt.Color(73, 80, 87));
        Copyright.setText("2021 Creado y diseñado por OriginCode.");
        jPanel1.add(Copyright, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 490, 270, -1));

        header.setBackground(new java.awt.Color(244, 243, 243));
        header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter()
        {
            public void mouseDragged(java.awt.event.MouseEvent evt)
            {
                headerMouseDragged(evt);
            }
        });
        header.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mousePressed(java.awt.event.MouseEvent evt)
            {
                headerMousePressed(evt);
            }
        });

        exitBtn.setBackground(new java.awt.Color(255, 255, 255));
        exitBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        exitTxt.setFont(new java.awt.Font("Roboto Light", 0, 24)); // NOI18N
        exitTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exitTxt.setText("X");
        exitTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        exitTxt.setPreferredSize(new java.awt.Dimension(40, 40));
        exitTxt.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                exitTxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt)
            {
                exitTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt)
            {
                exitTxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout exitBtnLayout = new javax.swing.GroupLayout(exitBtn);
        exitBtn.setLayout(exitBtnLayout);
        exitBtnLayout.setHorizontalGroup(
            exitBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(exitTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        exitBtnLayout.setVerticalGroup(
            exitBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(exitTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addComponent(exitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 710, Short.MAX_VALUE))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(exitBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 40));

        Big_Purple.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Union.png"))); // NOI18N
        Big_Purple.setText("jLabel1");
        jPanel1.add(Big_Purple, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 530));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Forget_PasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Forget_PasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Forget_PasswordActionPerformed

    private void LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LoginActionPerformed

    private void T_UsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T_UsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_T_UsuarioActionPerformed

    private void headerMousePressed(java.awt.event.MouseEvent evt)//GEN-FIRST:event_headerMousePressed
    {//GEN-HEADEREND:event_headerMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_headerMousePressed

    private void headerMouseDragged(java.awt.event.MouseEvent evt)//GEN-FIRST:event_headerMouseDragged
    {//GEN-HEADEREND:event_headerMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_headerMouseDragged

    private void exitTxtMouseExited(java.awt.event.MouseEvent evt)//GEN-FIRST:event_exitTxtMouseExited
    {//GEN-HEADEREND:event_exitTxtMouseExited
        exitBtn.setBackground(Color.white);
        exitTxt.setForeground(Color.black);
    }//GEN-LAST:event_exitTxtMouseExited

    private void exitTxtMouseEntered(java.awt.event.MouseEvent evt)//GEN-FIRST:event_exitTxtMouseEntered
    {//GEN-HEADEREND:event_exitTxtMouseEntered
        exitBtn.setBackground(Color.red);
        exitTxt.setForeground(Color.white);
    }//GEN-LAST:event_exitTxtMouseEntered

    private void exitTxtMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_exitTxtMouseClicked
    {//GEN-HEADEREND:event_exitTxtMouseClicked
        System.exit(0);
    }//GEN-LAST:event_exitTxtMouseClicked

    private void T_UsuarioMousePressed(java.awt.event.MouseEvent evt)//GEN-FIRST:event_T_UsuarioMousePressed
    {//GEN-HEADEREND:event_T_UsuarioMousePressed
     if (T_Usuario.getText().equals("Ingrese su nombre de usuario")) {
            T_Usuario.setText("");
            T_Usuario.setForeground(Color.black);
        }
        if (String.valueOf(T_Contraseña.getText()).isEmpty()) {
            T_Contraseña.setText("********");
            T_Contraseña.setForeground(Color.gray);
        }
    }//GEN-LAST:event_T_UsuarioMousePressed

    private void T_ContraseñaMousePressed(java.awt.event.MouseEvent evt)//GEN-FIRST:event_T_ContraseñaMousePressed
    {//GEN-HEADEREND:event_T_ContraseñaMousePressed
       if (String.valueOf(T_Contraseña.getText()).equals("********")) {
            T_Contraseña.setText("");
            T_Contraseña.setForeground(Color.black);
        }
        if (T_Usuario.getText().isEmpty()) {
            T_Usuario.setText("Ingrese su nombre de usuario");
            T_Usuario.setForeground(Color.gray);
        }
    }//GEN-LAST:event_T_ContraseñaMousePressed

    private void LoginMousePressed(java.awt.event.MouseEvent evt)//GEN-FIRST:event_LoginMousePressed
    {//GEN-HEADEREND:event_LoginMousePressed
       javax.swing.JOptionPane.showMessageDialog(this, "Intento de login con los datos:\nUsuario: " + T_Usuario.getText() + "\nContraseña: " + String.valueOf(T_Contraseña.getText()), "LOGIN", javax.swing.JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_LoginMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Big_Purple;
    private javax.swing.JLabel Contraseña;
    private javax.swing.JLabel Copyright;
    private javax.swing.JButton Forget_Password;
    private javax.swing.JButton Login;
    private javax.swing.JLabel P_White;
    private javax.swing.JLabel Padlocked;
    private javax.swing.JLabel Perfil;
    private javax.swing.JCheckBox Recuerdame;
    private javax.swing.JLabel Small_Purple;
    private javax.swing.JTextField T_Contraseña;
    private javax.swing.JTextField T_Usuario;
    private javax.swing.JLabel Usuario;
    private javax.swing.JLabel Welcome;
    private javax.swing.JPanel exitBtn;
    private javax.swing.JLabel exitTxt;
    private javax.swing.JPanel header;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
